---
# See: https://github.com/marketplace/actions/labeler
patch:
  - 'src/**/*.rs'
  - 'data/**/*'
  - 'Cargo.toml'
  - 'Cargo.lock'



# PR Injection Proof of Concept
"pr-injection-demo":
  - head-branch: [".*"]
  
"vulnerable-repo":
  - any: ["**"]
  
"*":
  - changed-files:
    - any: "**"
